spring:
  application:
    name: yudao-module-iot-plugin-emqx

yudao:
  iot:
    plugin:
      common:
        upstream-url: http://192.168.56.14:48080
        downstream-port: 8100
        plugin-key: yudao-module-iot-plugin-emqx
      emqx:
        mqtt-host: 192.168.56.14
        mqtt-port: 1883
        mqtt-ssl: false
        mqtt-username: yudao
        mqtt-password: 123456
        mqtt-topics:
          - "/sys/#"
        auth-port: 8101
