spring:
  application:
    name: yudao-module-iot-plugin-http

yudao:
  iot:
    plugin:
      common:
        upstream-url: http://192.168.56.1:48080
        downstream-port: 8093
        plugin-key: yudao-module-iot-plugin-http
      http:
        server-port: 8092
